version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - authentication-service
      - notification-service
    networks:
      - app-network

  authentication-service:
    build:
      context: .
      dockerfile: ./services/authentication-service/Dockerfile
    environment:
      - AUTH_PORT=4000
      - AUTH_DB_URL=${AUTH_DB_URL}
      - AUTH_JWT_ACCESS_PRIVATE_KEY=${AUTH_JWT_ACCESS_PRIVATE_KEY}
      - AUTH_JWT_REFRESH_PRIVATE_KEY=${AUTH_JWT_REFRESH_PRIVATE_KEY}
      - AUTH_ACCESS_TOKEN_TTL=${AUTH_ACCESS_TOKEN_TTL:-900}
      - AUTH_REFRESH_TOKEN_TTL=${AUTH_REFRESH_TOKEN_TTL:-2592000}
    networks:
      - app-network

  notification-service:
    build:
      context: .
      dockerfile: ./services/notification-service/Dockerfile
    environment:
      - NOTIFY_PORT=4000
      - NOTIFY_SMTP_URL=${NOTIFY_SMTP_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
